baseURL : https://demo.uicard.io/hugo-sodium/
languageCode : en-us
title : Sodium
theme : hugo-sodium-theme

taxonomies:
  category: categories
  tag: tags

params:
  social:
    facebook: loopclinical
    instagram: loopclinical
    twitter: loopclinical

  scripts:
    googleanalytics: "UA-113081075-1"
    disqus: 
    
