baseURL : https://lyftgalactic.com/
languageCode : en-us
title : Lyft Galactic
theme : hugo-sodium-theme

taxonomies:
  category: categories
  tag: tags

params:
  social:
    facebook: lyftgalactic
    instagram: lyftgalactic
    twitter: lyftgalactic

  scripts:
    googleanalytics: "UA-113081075-1"
    disqus: 
    
